文法丨其它->其他丨为包含顿号（、）的标题提供跳转支持
ryanhanwu/How-To-Ask-Questions-The-Smart-Way pull request #125
Opened 2021-01-25 01:30 UTC by WuzgXY-GitHub

事实上按照权威词典的解释「其它」不如「其他」规范，但考虑到「其它」有助于区分讨论对象的类别并且它符合较多人的阅读/书写习惯，因此仅对错误之处作修改

很抱歉上次 [PR](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/pull/71) 时未意识到当时所修改的那一节之目录仍未能正确提供跳转

2021-01-31 01:02 UTC, xiaopangju requested changes

2021-01-31 02:14 UTC, WuzgXY-GitHub commented on README-zh_CN.md
> +请记得，还有其他许多使用者没遇到你发现的问题，否则你在阅读文件或搜索网页时就应该发现了（你在抱怨前[已经做了这些，是吧](#在提问之前)？）。这也意味着很有可能是你弄错了而不是软件本身有问题。
已修正，感谢提醒！

2021-01-31 03:19 UTC, xiaopangju approved these changes

2021-01-31 03:20 UTC, xiaopangju commented
@WuzgXY-GitHub 没什么问题了，感谢你的贡献

2021-02-27 06:00 UTC, xiaopangju commented
@ryanhanwu 请问您可以合并这个PR吗？这个PR关系到使用者/用户阅读本文时的舒适度！

2021-02-27 06:53 UTC, PercyDan54 commented on README-zh_CN.md
> +**如果帮不了忙，也别妨碍他。**不要在实际步骤上开玩笑，那样也许会毁了使用者的设置 —— 有些可怜的呆瓜会把它当成真的指令。
```suggestion
**如果帮不了忙，也别妨碍他。**不要在实际步骤上开玩笑，那样也许会毁了用户的设置 —— 有些可怜的呆瓜会把它当成真的指令。
```

2021-02-27 14:52 UTC, WuzgXY-GitHub commented on README-zh_CN.md
> +**如果帮不了忙，也别妨碍他。**不要在实际步骤上开玩笑，那样也许会毁了使用者的设置 —— 有些可怜的呆瓜会把它当成真的指令。
```suggestion
**如果帮不了忙，也别妨碍他。**不要在实际步骤上开玩笑，那样也许会毁了提问者的设置 —— 有些可怜的呆瓜会把它当成真的指令。
```

2021-02-27 14:53 UTC, WuzgXY-GitHub commented on README-zh_CN.md
> +**如果帮不了忙，也别妨碍他。**不要在实际步骤上开玩笑，那样也许会毁了使用者的设置 —— 有些可怜的呆瓜会把它当成真的指令。
此处我认为「使用者」较「用户」贴切，于是保留了使用者这一用法。现在看来其实有更好的选择，没问题的话我就合自己的 suggestion 了

2021-02-28 01:57 UTC, xiaopangju commented on README-zh_CN.md
> +**如果帮不了忙，也别妨碍他。**不要在实际步骤上开玩笑，那样也许会毁了使用者的设置 —— 有些可怜的呆瓜会把它当成真的指令。
> 
> 
> 此处我认为「使用者」较「用户」贴切，于是保留了使用者这一用法。现在看来其实有更好的选择，没问题的话我就合自己的 suggestion 了

确实，在这个语境下，“提问者”确实比“使用者”好

2021-08-01 16:15 UTC, ryanhanwu requested changes
The text changes are good, just replace the quotes with straight quotes.

2021-08-01 16:15 UTC, ryanhanwu commented on README-zh_CN.md
> +别像机关枪似的一次“扫射”所有的帮助渠道，这就像大喊大叫一样会使人不快。要一个一个地来。
Can you use regular quotes instead of smart quotes?

2021-08-01 16:15 UTC, ryanhanwu commented on README-zh_CN.md
> +事实上，如果程序出的问题只发生在特定 Linux 发行版提供的版本（这很常见），最好先去该发行版的论坛或邮件列表中提问，再到程序本身的论坛或邮件列表提问。（否则）该项目的黑客可能仅仅回复 “使用**我们的**版本”。
Same here

2021-08-02 01:30 UTC, WuzgXY-GitHub commented
As a passage in Chinese, the quote marks (and other marks) it contains should be full-width.
Maybe right-angle quote marks (「」『』) are a good substitute in Chinese parts, because it is specifically designed for full-width characters like CJKV characters.

2021-09-29 04:16 UTC, merged