Update translation
ryanhanwu/How-To-Ask-Questions-The-Smart-Way pull request #145
Opened 2022-02-05 09:06 UTC by liijunwei

+ http://www.catb.org/~esr/faqs/smart-questions.html
+ original: "Now that use of open source has become widespread, you can often get as good answers from other, more experienced users as from hackers. This is a Good Thing; users tend to be just a little bit more tolerant of the kind of failures newbies often have. Still, treating experienced users like hackers in the ways we recommend here will generally be the most effective way to get useful answers out of them, too."

2022-02-08 02:44 UTC, ryanhanwu commented on README.md
> +現在開源（Open Source）軟件已經相當盛行，您通常可以從其他更有經驗的用戶那裡獲得與黑客一樣好的答案，這是件**好事**；和黑客相比，用戶們往往對那些新手常遇到的問題更寬容一些。儘管如此，以我們在此推薦的方式對待這些有經驗的用戶通常也是從他們那裡獲得有用答案的最有效方式。
在繁體中文仍是使用"軟體" 居多，可以煩請修正一下，感謝！

2022-02-08 02:44 UTC, ryanhanwu requested changes
Thanks!

2022-02-08 23:56 UTC, liijunwei commented on README.md
> +現在開源（Open Source）軟件已經相當盛行，您通常可以從其他更有經驗的用戶那裡獲得與黑客一樣好的答案，這是件**好事**；和黑客相比，用戶們往往對那些新手常遇到的問題更寬容一些。儘管如此，以我們在此推薦的方式對待這些有經驗的用戶通常也是從他們那裡獲得有用答案的最有效方式。
Fixed.

2022-02-14 01:55 UTC, ryanhanwu approved these changes
Much appreciated!

2022-02-14 01:55 UTC, merged