Add missing translation.
ryanhanwu/How-To-Ask-Questions-The-Smart-Way pull request #152
Opened 2022-03-19 01:55 UTC by liijunwei

+ [Ayx03](https://github.com/Ayx03)发现了翻译缺失 https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/pull/149#pullrequestreview-902514992
+ [original](http://www.catb.org/~esr/faqs/smart-questions.html)
> If you still didn't find anything, post your question on the one site where it's most on-topic. Use the formatting tools, especially for code, and add tags that are related to the substance of your question (particularly the name of the programming language, operating system, or library you're having trouble with). If a commenter asks you for more information, edit your main post to include it. If any answer is helpful, click the up arrow to upvote it; if an answer gives a solution to your problem, click the check under the voting arrows to accept it as correct.

2022-03-19 01:57 UTC, liijunwei commented
繁体中文 为google translate的结果，表达方式可能有问题， 请指出或者帮忙修改😅

2022-03-19 14:58 UTC, kang8 requested changes
翻译优化，一些建议

2022-03-19 14:58 UTC, kang8 commented on README-zh_CN.md
> +如果你仍然没有找到任何线索，请将你的问题发布在最贴合主题的网站上。把问题描述清楚，把代码格式调好，然后添加与你问题内容相关的标签(特别是你遇到问题的编程语言、操作系统或库的名称)。如果评论者要求你提供更多信息，请在你的帖子里补充这些信息。 如果答案有帮助，请点击向上箭头为它点赞；如果答案解决了你的问题，请点击投票箭头下的复选框把它设为问题的答案。
```suggestion
如果你仍然没有找到任何线索，请将你的问题发布在最贴合主题的网站上。把问题描述清楚，把代码格式调好，然后添加与你问题内容相关的标签(如你遇到问题的编程语言、操作系统或库的名称)。如果评论者要求你提供更多信息，请在你的帖子里一并补充。 如果答案有帮助，请点击向上箭头为它点赞；如果答案解决了你的问题，请点击投票箭头下的复选框把它设为问题的答案。
```

2022-03-20 08:20 UTC, liijunwei commented on README-zh_CN.md
> +如果你仍然没有找到任何线索，请将你的问题发布在最贴合主题的网站上。把问题描述清楚，把代码格式调好，然后添加与你问题内容相关的标签(特别是你遇到问题的编程语言、操作系统或库的名称)。如果评论者要求你提供更多信息，请在你的帖子里补充这些信息。 如果答案有帮助，请点击向上箭头为它点赞；如果答案解决了你的问题，请点击投票箭头下的复选框把它设为问题的答案。
前面的"particularly"我建议保留它的含义；后面的改动我认为很合理, 我改一下
谢谢你 @kang8

2022-03-20 11:50 UTC, kang8 approved these changes

2022-04-01 06:54 UTC, closed without merging